
run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  tests: false
  skip-dirs-use-default: true
  skip-files:
    - ".*\\.bad\\.go$"

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - goconst
    - funlen
    - bodyclose
    - errcheck
    - deadcode
    - exportloopref

linters-settings:
  goimports:
    local-prefixes: path/to/module
  govet:
    check-shadowing: true
  goconst:
    min-len: 2
    min-occurrences: 2
  funlen:
    lines: 100
    statements: 50
